/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_adc.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_dac.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Definition of the clock source frequency. */
#define ADC0_CLK_FREQ 30000000UL
/* ADC0 interrupt vector ID (number). */
#define ADC0_ADC_SEQ_A_IRQN ADC0_SEQA_IRQn
/* ADC0 interrupt handler identifier. */
#define ADC0_ADC_SEQ_A_IRQHANDLER ADC0_SEQA_IRQHandler
/* BOARD_InitPeripherals defines for USART0 */
/* Definition of peripheral ID */
#define USART0_PERIPHERAL ((USART_Type *)USART0)
/* Definition of the clock source frequency */
#define USART0_CLOCK_SOURCE 15000000UL
/* BOARD_InitPeripherals defines for DAC0 */
/* Definition of peripheral ID */
#define DAC0_PERIPHERAL ((DAC_Type *) DAC0_BASE)
/* Definition of DAC output value. */
#define DAC0_BUFFER_VALUE 0
/* Definition of DAC counter value. */
#define DAC0_COUNTER_VALUE 0
/* DAC0 interrupt vector ID (number). */
#define DAC0_IRQN DAC0_IRQn
/* DAC0 interrupt handler identifier. */
#define DAC0_IRQHANDLER DAC0_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const adc_config_t ADC0configStruct;
extern const adc_conv_seq_config_t ADC0ConvSeqAConfigStruct;
extern const usart_config_t USART0_config;
extern const dac_config_t DAC0_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
