/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: LPC845
package_id: LPC845M301JBD48
mcu_data: ksdk2_0
processor_version: 12.0.0
board: LPC845BREAKOUT
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a1bf1abb-ba15-4a89-8c58-09436b4ba743
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'lpc_dma'
- mode: 'basic'
- custom_name_enabled: 'false'
- type_id: 'lpc_dma_c13ca997a68f2ca6c666916ba13db7d7'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_dma:
    - dma_table:
      - 0: []
    - dma_channels:
      - 0:
        - apiMode: 'trans'
        - dma_channel:
          - channel_prefix_id: 'CH0'
          - DMA_source: 'kDmaRequestDAC0_DMAREQ '
          - init_channel_priority: 'false'
          - dma_priority: 'kDMA_ChannelPriority0'
          - enable_custom_name: 'false'
        - peripheral_request: 'false'
        - init_trigger_config: 'false'
        - trigger_config:
          - type: 'kDMA_RisingEdgeTrigger'
          - burst: 'kDMA_SingleTransfer'
          - wrap: 'kDMA_NoWrap'
        - trans_config:
          - init_callback: 'true'
          - callback_function: 'Callback_DMA0_CH0'
          - callback_user_data: ''
        - tcd_config:
          - 0:
            - tcdID: 'CH0_TCD0'
            - linkToNextTCD: '0'
            - transferCfg:
              - reload: 'true'
              - clrTrig: 'true'
              - intA: 'true'
              - intB: 'false'
              - width: 'kDMA_Transfer32BitWidth'
              - srcInc: 'kDMA_AddressInterleave1xWidth'
              - dstInc: 'kDMA_AddressInterleave0xWidth'
              - transBytes: '8'
            - srcAddr:
              - addrType: 'startAddr'
              - addr_expr: '&SrcAddr[0]'
              - addr_def: 'uint32_t SrcAddr[8]'
            - dstAddr:
              - addrType: 'startAddr'
              - addr_expr: '0x40014000'
              - addr_def: ''
        - allocateTCD: 'noncache'
        - initTCD: 'CH0_TCD0'
    - dma_interrupt_trans:
      - IRQn: 'DMA0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

  /* Channel CH0 global variables */
dma_handle_t DMA0_CH0_Handle;
AT_NONCACHEABLE_SECTION_ALIGN(dma_descriptor_t DMA0_CH0_TCDs_config[1], FSL_FEATURE_DMA_LINK_DESCRIPTOR_ALIGN_SIZE)
 = {
  {
    .xfercfg = DMA_CHANNEL_XFER(true, true, true, false, kDMA_Transfer32BitWidth, kDMA_AddressInterleave1xWidth, kDMA_AddressInterleave0xWidth, 8U),
    .srcEndAddr = (void *)DMA_DESCRIPTOR_END_ADDRESS(&SrcAddr[0], (uint32_t)kDMA_AddressInterleave1xWidth, 8U, (uint32_t)kDMA_Transfer32BitWidth),
    .dstEndAddr = (void *)DMA_DESCRIPTOR_END_ADDRESS(0x40014000, (uint32_t)kDMA_AddressInterleave0xWidth, 8U, (uint32_t)kDMA_Transfer32BitWidth),
    .linkToNextDesc = &DMA0_CH0_TCD0_config
  }
};

static void DMA0_init(void) {

  /* Channel CH0 initialization */
  /* Enable the DMA 22 channel in the DMA */
  DMA_EnableChannel(DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  /* Create the DMA DMA0_CH0_Handle handle */
  DMA_CreateHandle(&DMA0_CH0_Handle, DMA0_DMA_BASEADDR, DMA0_CH0_DMA_CHANNEL);
  DMA_SetCallback(&DMA0_CH0_Handle, Callback_DMA0_CH0, NULL);
  /* DMA0 transfer submit */
  DMA_SubmitChannelDescriptor(&DMA0_CH0_Handle, &DMA0_CH0_TCD0_config);
}

/***********************************************************************************************************************
 * DAC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DAC0'
- type: 'lpc_dac'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'lpc_dac_be609e98c6bf7f417ccc66d577e5bc39'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DAC0'
- config_sets:
  - general:
    - general_config:
      - clockSource: 'BusInterfaceClock'
      - clockSourceFreq: 'BOARD_BootClockFRO18M'
      - settlingTime: 'kDAC_SettlingTimeIs1us'
    - enable_double_buffer: 'true'
    - buffer_value_input: '0'
    - counter_value_input: '3000'
    - enable_dma: 'true'
    - enable_counter: 'true'
    - enableInterrupt: 'false'
    - interrupt:
      - IRQn: 'DAC0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const dac_config_t DAC0_config = {
  .settlingTime = kDAC_SettlingTimeIs1us
};

static void DAC0_init(void) {
  /* DAC0 initiation  */
  DAC_Init(DAC0_PERIPHERAL, &DAC0_config);
  /* DAC0 double buffering enabled */
  DAC_EnableDoubleBuffering(DAC0_PERIPHERAL, true);
  /* DAC0 set buffer value */
  DAC_SetBufferValue(DAC0_PERIPHERAL, DAC0_BUFFER_VALUE);
  /* DAC0 set counter value */
  DAC_SetCounterValue(DAC0_PERIPHERAL, DAC0_COUNTER_VALUE);
  /* DAC0 DMA access enabled */
  DAC_EnableDMA(DAC0_PERIPHERAL, true);
  /* DAC0 enable counter */
  DAC_EnableCounter(DAC0_PERIPHERAL, true);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  DMA_Init(DMA0_DMA_BASEADDR);

  /* Initialize components */
  DMA0_init();
  DAC0_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
